-- V1__init_schema.sql
-- Flyway migration script creating 11 core tables compatible with PostgreSQL and H2

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    address VARCHAR(500),
    phone VARCHAR(50),
    status VARCHAR(50)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE,
    password VARCHAR(255),
    full_name VARCHAR(255),
    role_id BIGINT REFERENCES roles(id),
    branch_id BIGINT REFERENCES branches(id),
    enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE dishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    image_url VARCHAR(1000),
    category VARCHAR(100),
    is_available BOOLEAN DEFAULT TRUE,
    branch_id BIGINT REFERENCES branches(id)
);

CREATE TABLE restaurant_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number VARCHAR(50),
    status VARCHAR(50),
    branch_id BIGINT REFERENCES branches(id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name VARCHAR(255),
    quantity DOUBLE PRECISION,
    unit VARCHAR(50),
    min_threshold DOUBLE PRECISION,
    branch_id BIGINT REFERENCES branches(id)
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id BIGINT REFERENCES dishes(id),
    branch_id BIGINT REFERENCES branches(id)
);

CREATE TABLE recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_name VARCHAR(255),
    amount DOUBLE PRECISION,
    unit VARCHAR(50)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES restaurant_tables(id),
    customer_name VARCHAR(255),
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(50) NOT NULL DEFAULT 'CASH',
    payment_status VARCHAR(50) NOT NULL DEFAULT 'UNPAID',
    created_at TIMESTAMP NOT NULL,
    branch_id BIGINT REFERENCES branches(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    dish_id BIGINT NOT NULL REFERENCES dishes(id),
    quantity INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    ip_address VARCHAR(255),
    description VARCHAR(1000)
);
