CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id), branch_id BIGINT NOT NULL REFERENCES branches(id),
    transaction_type VARCHAR(20) NOT NULL, payment_method VARCHAR(30) NOT NULL,
    amount NUMERIC(19, 0) NOT NULL, amount_tendered NUMERIC(19, 0), change_amount NUMERIC(19, 0),
    status VARCHAR(20) NOT NULL, reference_code VARCHAR(100), note VARCHAR(500),
    created_at TIMESTAMP NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), completed_at TIMESTAMP,
    version BIGINT DEFAULT 0 NOT NULL, CONSTRAINT chk_payment_transaction_amount CHECK (amount > 0)
);
CREATE INDEX idx_payment_transactions_order_id ON payment_transactions(order_id);
CREATE INDEX idx_payment_transactions_branch_id ON payment_transactions(branch_id);
CREATE INDEX idx_payment_transactions_status ON payment_transactions(status);
CREATE INDEX idx_payment_transactions_created_at ON payment_transactions(created_at);
