ALTER TABLE inventory ALTER COLUMN quantity NUMERIC(19, 3);
ALTER TABLE inventory ALTER COLUMN min_threshold NUMERIC(19, 3);
ALTER TABLE inventory ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE recipe_items ALTER COLUMN amount NUMERIC(19, 3);
ALTER TABLE recipe_items ADD COLUMN inventory_item_id BIGINT;
UPDATE recipe_items ri SET inventory_item_id = (
    SELECT i.id FROM inventory i JOIN recipes r ON r.id = ri.recipe_id
    WHERE i.branch_id = r.branch_id AND i.ingredient_name = ri.ingredient_name
);
ALTER TABLE recipe_items ADD CONSTRAINT fk_recipe_items_inventory FOREIGN KEY (inventory_item_id) REFERENCES inventory(id);
CREATE INDEX idx_recipe_items_inventory_item_id ON recipe_items(inventory_item_id);

CREATE TABLE inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES inventory(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    transaction_type VARCHAR(30) NOT NULL,
    quantity NUMERIC(19, 3) NOT NULL,
    quantity_before NUMERIC(19, 3) NOT NULL,
    quantity_after NUMERIC(19, 3) NOT NULL,
    reference_type VARCHAR(30), reference_id BIGINT, reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL, created_by BIGINT REFERENCES users(id),
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT chk_inventory_transaction_quantity CHECK (quantity > 0)
);
CREATE INDEX idx_inventory_transactions_branch_id ON inventory_transactions(branch_id);
CREATE INDEX idx_inventory_transactions_inventory_item_id ON inventory_transactions(inventory_item_id);
CREATE INDEX idx_inventory_transactions_created_at ON inventory_transactions(created_at);
CREATE INDEX idx_inventory_transactions_type ON inventory_transactions(transaction_type);
CREATE INDEX idx_inventory_transactions_reference ON inventory_transactions(reference_type, reference_id);
