CREATE TABLE work_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    cashier_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    opening_cash NUMERIC(19, 0) NOT NULL,
    expected_cash NUMERIC(19, 0), actual_cash NUMERIC(19, 0), cash_difference NUMERIC(19, 0),
    total_sales NUMERIC(19, 0), cash_sales NUMERIC(19, 0), transfer_sales NUMERIC(19, 0),
    card_sales NUMERIC(19, 0), refund_total NUMERIC(19, 0),
    order_count BIGINT NOT NULL DEFAULT 0,
    note VARCHAR(500),
    opened_by BIGINT NOT NULL REFERENCES users(id),
    closed_by BIGINT REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_work_shift_opening_cash CHECK (opening_cash >= 0),
    CONSTRAINT chk_work_shift_actual_cash CHECK (actual_cash IS NULL OR actual_cash >= 0)
);
CREATE INDEX idx_work_shifts_branch_id ON work_shifts(branch_id);
CREATE INDEX idx_work_shifts_cashier_id ON work_shifts(cashier_id);
CREATE INDEX idx_work_shifts_status ON work_shifts(status);
CREATE INDEX idx_work_shifts_opened_at ON work_shifts(opened_at);
CREATE INDEX idx_work_shifts_closed_at ON work_shifts(closed_at);

ALTER TABLE payment_transactions ADD COLUMN work_shift_id BIGINT REFERENCES work_shifts(id);
CREATE INDEX idx_payment_transactions_work_shift_id ON payment_transactions(work_shift_id);

ALTER TABLE activity_logs ADD COLUMN branch_id BIGINT REFERENCES branches(id);
ALTER TABLE activity_logs ADD COLUMN entity_type VARCHAR(80);
ALTER TABLE activity_logs ADD COLUMN entity_id BIGINT;
ALTER TABLE activity_logs ADD COLUMN metadata VARCHAR(2000);
CREATE INDEX idx_activity_logs_branch_id ON activity_logs(branch_id);
CREATE INDEX idx_activity_logs_action ON activity_logs(action);
CREATE INDEX idx_activity_logs_timestamp ON activity_logs(timestamp);
